spring:
  application.name: real_time_leaderboard
  profiles.active: dev
  config:
    import: optional:file:.env[.properties]
  data.redis:
    host: localhost
    port: 6379
    password: password
    timeout: 2000
    database: 0
    ssl:
      enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes

server.servlet.context-path: /api/v1

jwt:
  secret-key: ${SECRET_KEY}
